#include <stdio.h>
#include <stdlib.h>
#include <stdbool.h>
#include <sys/stat.h>
#include <unistd.h>
void menu();
void CreatNewFile();
void WriteFile();
void GetFileName();
void ReadFile();
void ChangePower();
void WatchPower();
